Getting a powerupobject to spawn
mbpautz762/gauntlet pull request #33
Opened 2021-07-22 20:44 UTC by cab0323

Implementing the PowerUp game object

2021-07-23 21:19 UTC, divpatel10 requested changes
Waiting for the PowerUpSpec and PowerUpSpawnComponent Files, other changes looks great!

2021-07-26 16:41 UTC, cab0323 commented
Committing the PowerUp classes

2021-07-27 15:29 UTC, divpatel10 commented on app/src/main/java/com/example/gauntlet/GameEngine.java
> +      objects.get(Level.FIRST_ALIEN).spawn(objects.get(Level.PLAYER_INDEX).getTransform());
May need to comment this out after merge

2021-07-27 15:30 UTC, divpatel10 commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
Change back to Gradle version 6.5 after merge

2021-07-27 15:31 UTC, merged